# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161117_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1970),
        ),
    ]
