# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_auto_20170122_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exerpt',
            field=models.TextField(default=''),
        ),
    ]
