# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 13:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20170122_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
