# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0013_author_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='app.Author'),
        ),
    ]
