# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 14:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_auto_20170122_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app.Author'),
        ),
    ]
