# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0015_auto_20170122_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authors',
            new_name='author',
        ),
    ]
